import os
import json
import datetime
from typing import List, Optional
from pydantic import BaseModel
from fastapi import APIRouter

from core.config import PIPELINE_DIR

router = APIRouter(prefix="/api", tags=["Configuration"])

class TrackerSetupRequest(BaseModel):
    protected_attributes: List[dict]
    target_variable: dict
    pipeline_scripts: Optional[List[dict]] = []

@router.post("/tracker/setup")
def setup_tracker(request: TrackerSetupRequest):
    """
    Dynamically generates backend/pipeline/tracker_setup.py with the user's
    configured protected demographic attributes and target variable.
    """
    os.makedirs(PIPELINE_DIR, exist_ok=True)

    # Normalize protected attributes (types must be 'categorical' or 'continuous')
    clean_attributes = []
    for attr in request.protected_attributes:
        name = str(attr.get("name", "")).strip()
        attr_type = str(attr.get("type", "")).strip().lower()
        if attr_type not in ["categorical", "continuous"]:
            attr_type = "categorical"
        clean_attributes.append({"name": name, "type": attr_type})

    # Normalize target variable
    target_name = str(request.target_variable.get("name", "")).strip()
    pos_val = str(request.target_variable.get("positive", "")).strip()
    neg_val = str(request.target_variable.get("negative", "")).strip()
    clean_target = {
        "name": target_name,
        "positive": pos_val,
        "negative": neg_val
    }

    config_data = {
        "protected_attributes": clean_attributes,
        "target_variable": clean_target,
        "pipeline_scripts": request.pipeline_scripts or [],
        "updated_at": datetime.datetime.now().isoformat()
    }

    # Save JSON cache
    config_json_path = os.path.join(PIPELINE_DIR, "tracker_config.json")
    with open(config_json_path, "w", encoding="utf-8") as f:
        json.dump(config_data, f, indent=4)

    # Generate tracker_setup.py
    tracker_code = f"""# Auto-generated by PROBA Tracker Setup
# Generated on: {datetime.datetime.now().isoformat()}
import os
import sys
import atexit

_current_dir = os.path.dirname(os.path.abspath(__file__))
_utils_dir = os.path.join(_current_dir, "utils")
if _utils_dir not in sys.path:
    sys.path.insert(0, _utils_dir)

try:
    from utils.provenance import ProvenanceMetadataTracker
except ImportError:
    from provenance import ProvenanceMetadataTracker

tracker = ProvenanceMetadataTracker(
    protected_attributes={clean_attributes!r},
    target_variable={clean_target!r}
)

def _auto_export_on_exit():
    # Automatically exports tracked provenance records at the end of the pipeline.
    if hasattr(tracker, 'metadata_records') and tracker.metadata_records:
        # Determine root directory for provenance_metadata.json
        root_dir = os.path.abspath(os.path.join(_current_dir, "..", ".."))
        json_path = os.path.join(root_dir, "provenance_metadata.json")
        try:
            tracker.export_to_database()
        except Exception as e:
            print(f"[Tracker] Notice: Could not export to DB ({{e}}), falling back to JSON.")
        try:
            tracker.export_to_json(json_path)
            print(f"[Tracker] Auto-exported {{len(tracker.metadata_records)}} provenance records to {{json_path}}")
        except Exception as e:
            print(f"[Tracker] Error exporting to JSON: {{e}}")

atexit.register(_auto_export_on_exit)
"""
    tracker_file_path = os.path.join(PIPELINE_DIR, "tracker_setup.py")
    with open(tracker_file_path, "w", encoding="utf-8") as f:
        f.write(tracker_code)

    print(f"[API] Generated dynamic tracker_setup.py with {len(clean_attributes)} attributes and target '{target_name}'.")

    return {
        "status": "success",
        "message": "tracker_setup.py generated successfully",
        "file_path": tracker_file_path,
        "config": config_data
    }
